import fs from "node:fs";
import path from "node:path";

/**
 * PactReader — reads pacts/*.json as source of truth (architecture-pact-v2.md §2.6)
 * No hardcode. Parses PactV3 JSON generated by p:consumer.
 * Used by Electron main (IPC) and by UI via window.playground.getPacts().
 */

export interface PactInteractionView {
  description: string;
  providerState?: string;
  providerStateParams?: Record<string, unknown>;
  request: {
    method: string;
    path: string;
    headers?: Record<string, string>;
    body?: unknown;
    matchingRules?: unknown;
  };
  response: {
    status: number;
    headers?: Record<string, string>;
    body?: unknown;
    matchingRules?: unknown;
  };
}

export interface PactContractView {
  consumer: string; // "playground-F01"
  provider: string; // "FactoryProvider"
  featureId: string; // "F01" derived from consumer
  pactFile: string; // absolute path
  pactFileRelative: string; // relative to repo root, e.g. "software-testing-playground-v2/pacts/playground-F01-FactoryProvider.json"
  interactions: PactInteractionView[];
  metadata?: unknown;
  generatedAt?: string;
}

const PACTS_DIR = path.resolve("software-testing-playground-v2/pacts");
const RELATIVE_PACTS_DIR = "software-testing-playground-v2/pacts";

/**
 * Derive featureId from consumer name "playground-F01" -> "F01"
 * Falls back to parsing file name if consumer missing.
 */
function deriveFeatureId(raw: unknown, fileName: string): string {
  const consumerName =
    typeof raw === "object" && raw !== null && "consumer" in raw && typeof (raw as { consumer: unknown }).consumer === "object"
      ? ((raw as { consumer: { name?: unknown } }).consumer.name as string | undefined)
      : undefined;
  if (consumerName && consumerName.startsWith("playground-")) {
    return consumerName.replace("playground-", "").toUpperCase();
  }
  // fallback from file: playground-F01-FactoryProvider.json
  const match = fileName.match(/playground-(F\d{2})-FactoryProvider\.json/i);
  if (match) return match[1].toUpperCase();
  // last resort
  return fileName.replace(/[^F0-9]/g, "").slice(0, 3).toUpperCase() || "F??";
}

function parseInteraction(raw: unknown): PactInteractionView | null {
  if (!raw || typeof raw !== "object") return null;
  const r = raw as Record<string, unknown>;
  const description = typeof r.description === "string" ? r.description : "interaction";
  // providerState can be "providerState" (old) or "providerStates" array (PactV3)
  let providerState: string | undefined;
  let providerStateParams: Record<string, unknown> | undefined;
  if (typeof r.providerState === "string") {
    providerState = r.providerState as string;
  } else if (Array.isArray(r.providerStates) && r.providerStates.length > 0) {
    const first = r.providerStates[0] as Record<string, unknown>;
    if (typeof first?.name === "string") providerState = first.name;
    if (first?.params && typeof first.params === "object") providerStateParams = first.params as Record<string, unknown>;
  } else if (typeof r.providerStates === "string") {
    providerState = r.providerStates;
  }

  const requestRaw = (r.request ?? {}) as Record<string, unknown>;
  const responseRaw = (r.response ?? {}) as Record<string, unknown>;

  const reqHeaders =
    requestRaw.headers && typeof requestRaw.headers === "object"
      ? (requestRaw.headers as Record<string, string>)
      : undefined;
  const resHeaders =
    responseRaw.headers && typeof responseRaw.headers === "object"
      ? (responseRaw.headers as Record<string, string>)
      : undefined;

  return {
    description,
    providerState,
    providerStateParams,
    request: {
      method: typeof requestRaw.method === "string" ? (requestRaw.method as string).toUpperCase() : "GET",
      path: typeof requestRaw.path === "string" ? (requestRaw.path as string) : "/",
      headers: reqHeaders,
      body: requestRaw.body,
      matchingRules: requestRaw.matchingRules,
    },
    response: {
      status: typeof responseRaw.status === "number" ? (responseRaw.status as number) : 0,
      headers: resHeaders,
      body: responseRaw.body,
      matchingRules: responseRaw.matchingRules,
    },
  };
}

function toPactContractView(filePath: string, raw: unknown): PactContractView | null {
  if (!raw || typeof raw !== "object") return null;
  const r = raw as Record<string, unknown>;
  const consumerName =
    r.consumer && typeof r.consumer === "object" ? ((r.consumer as { name?: unknown }).name as string | undefined) : undefined;
  const providerName =
    r.provider && typeof r.provider === "object" ? ((r.provider as { name?: unknown }).name as string | undefined) : undefined;

  const fileName = path.basename(filePath);
  const featureId = deriveFeatureId(raw, fileName);
  const rawInteractions = Array.isArray(r.interactions) ? (r.interactions as unknown[]) : Array.isArray(r.messages) ? (r.messages as unknown[]) : [];

  const interactions = rawInteractions.map(parseInteraction).filter(Boolean) as PactInteractionView[];

  const relative = path.join(RELATIVE_PACTS_DIR, fileName).replace(/\\/g, "/");

  // generatedAt: try pact metadata or file mtime fallback; spec says contractView.generatedAt
  let generatedAt: string | undefined;
  try {
    const stat = fs.statSync(filePath);
    generatedAt = stat.mtime.toISOString();
  } catch {
    generatedAt = new Date().toISOString();
  }

  return {
    consumer: consumerName ?? `playground-${featureId}`,
    provider: providerName ?? "FactoryProvider",
    featureId,
    pactFile: filePath,
    pactFileRelative: relative,
    interactions,
    metadata: r.metadata,
    generatedAt,
  };
}

/**
 * Lists all pact contracts by reading pacts/*.json.
 * Returns sorted by featureId (F01, F02...).
 * If dir missing or empty, returns [] (caller shows "No hay contrato Pact — corre pnpm p:consumer").
 */
export function listPactContracts(): PactContractView[] {
  try {
    if (!fs.existsSync(PACTS_DIR)) return [];
    const files = fs.readdirSync(PACTS_DIR).filter((f) => f.endsWith(".json"));
    const contracts: PactContractView[] = [];
    for (const file of files) {
      const full = path.join(PACTS_DIR, file);
      try {
        const rawText = fs.readFileSync(full, "utf-8");
        const raw = JSON.parse(rawText) as unknown;
        const view = toPactContractView(full, raw);
        if (view) contracts.push(view);
      } catch (e) {
        // Skip unreadable pact but still report as warning
        console.warn(`[pactReader] Failed to parse ${file}: ${String(e)}`);
      }
    }
    // sort by featureId natural
    contracts.sort((a, b) => a.featureId.localeCompare(b.featureId));
    return contracts;
  } catch (e) {
    console.warn(`[pactReader] listPactContracts failed: ${String(e)}`);
    return [];
  }
}

/**
 * Get single pact for a featureId, or null if not generated.
 */
export function getPactFor(featureId: string): PactContractView | null {
  const normalized = featureId.toUpperCase();
  const fileName = `playground-${normalized}-FactoryProvider.json`;
  const full = path.join(PACTS_DIR, fileName);
  if (!fs.existsSync(full)) return null;
  try {
    const raw = JSON.parse(fs.readFileSync(full, "utf-8")) as unknown;
    return toPactContractView(full, raw);
  } catch {
    return null;
  }
}

/**
 * Checks if pact JSON exists for featureId.
 */
export function pactExists(featureId: string): boolean {
  const normalized = featureId.toUpperCase();
  const full = path.join(PACTS_DIR, `playground-${normalized}-FactoryProvider.json`);
  return fs.existsSync(full);
}

/**
 * Returns raw JSON content for a pact file (for "Ver contrato JSON" link).
 * If file not exists, returns null.
 */
export function readPactRaw(featureId: string): unknown | null {
  const view = getPactFor(featureId);
  if (!view) return null;
  try {
    const raw = fs.readFileSync(view.pactFile, "utf-8");
    return JSON.parse(raw) as unknown;
  } catch {
    return null;
  }
}

export const PACTS_DIR_ABSOLUTE = PACTS_DIR;
export const PACTS_DIR_RELATIVE = RELATIVE_PACTS_DIR;
